[package]
name = "hello-webgpu"
version = "0.1.0"
authors = ["Lúcás Meier <cronokirby@gmail.com>"]
edition = "2018"

[dependencies]
cgmath = "0.17"
env_logger = "0.7"
futures = "0.3"
image = "0.23"
log = "0.4"
shaderc = "0.7"
wgpu = "0.6"
winit = "0.22"
